var searchData=
[
  ['r',['r',['../namespacegpu__test__theano__with__gpu.html#a2f8c6e8611f62576b821cb4e733323db',1,'gpu_test_theano_with_gpu']]],
  ['rbm_5fanalysis',['rbm_analysis',['../namespacerbm__analysis.html',1,'']]],
  ['rbm_5fanalysis_2epy',['rbm_analysis.py',['../rbm__analysis_8py.html',1,'']]],
  ['rbm_5flearn_5fmodel',['rbm_learn_model',['../namespacerbm__learn__model.html',1,'']]],
  ['rbm_5flearn_5fmodel_2epy',['rbm_learn_model.py',['../rbm__learn__model_8py.html',1,'']]],
  ['rbm_5frepresentation',['rbm_representation',['../namespacegenerate__new__representation.html#aa1841232bf54a03ae980ac06d452eafb',1,'generate_new_representation']]],
  ['readme_2emd',['README.md',['../_r_e_a_d_m_e_8md.html',1,'']]],
  ['report_2etxt',['report.txt',['../source_2report_8txt.html',1,'']]],
  ['report_2etxt',['report.txt',['../data_2new__representation_2rbm__4000_2report_8txt.html',1,'']]],
  ['report_5fasitis_2etxt',['Report_ASITIS.txt',['../_report___a_s_i_t_i_s_8txt.html',1,'']]],
  ['report_5flinearsvc_2etxt',['Report_LinearSVC.txt',['../_report___linear_s_v_c_8txt.html',1,'']]],
  ['report_5frbm_2etxt',['Report_RBM.txt',['../_report___r_b_m_8txt.html',1,'']]],
  ['rng',['rng',['../namespacegpu__test__theano__with__gpu.html#ac7da5aba65a6b03622bdc49a1f8e36a0',1,'gpu_test_theano_with_gpu']]],
  ['run_5fparallel_5fwith_5fasitis_5frepresentation',['run_parallel_with_ASITIS_representation',['../namespacebenchmark.html#aad20dde681f0a84b14b7fd59cf4e7ca5',1,'benchmark']]],
  ['run_5fparallel_5fwith_5flinearsvc_5ffeature_5fselection',['run_parallel_with_LinearSVC_feature_selection',['../namespacebenchmark.html#aaab065b4e101997f5d337f91ab66136f',1,'benchmark']]],
  ['run_5fparallel_5fwith_5frbm_5frepresentation',['run_parallel_with_RBM_representation',['../namespacebenchmark.html#a97df3222ef69a94ee7fc4c92636cb548',1,'benchmark']]]
];
